# Configuracao do Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# Configuracao do Spring MVC
spring.mvc.view.prefix=/WEB-INF/views/  # Se estiver usando JSP
spring.mvc.view.suffix=.jsp             # Se estiver usando JSP

logging.level.org.springframework=DEBUG
logging.level.com.example.demo=TRACE

server.servlet.context-path=/spring-mvc-forms
